CREATE TABLE climblog_log (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   
    climb_type TEXT NOT NULL,
    difficulty TEXT,
    attempts INT NOT NULL CHECK (attempts > 0),
    rating INT
);